### ISSUE TITLE
Invalid Glyph in pagination

### ISSUE THREAD

**Issue by JonasDralle** [rjl20/mastodon#10]
Your pagination is broken. "OLDR" doesn't look like an english word to me,

![image](https://user-images.githubusercontent.com/6533815/44616281-54981000-a84d-11e8-925e-bbaac3707107.png)

**Comment by rjl20** [comment]
Nor is "NWR". Hrm.

**Comment by rjl20** [comment]
Fixed in the code; will take effect next rebuild.
