### ISSUE TITLE
"/public" post list has fifth glyph

### ISSUE THREAD

**Issue by jack126guy** [rjl20/mastodon#16]
https://oulipo.social/public says "Browse a live stream of public posts from this server". I assume this should be "Look at public posts on Mastodon" like the link on the homepage.

**Comment by rjl20** [comment]
Oh, hm, probably. I'll check it out.

**Comment by jack126guy** [comment]
It says "Look at local public posts" now so I assume this was fixed ( 044d81a205ba33847a9b0938df3d9283df3e0108 ).
