### ISSUE TITLE
can't pass two-factor input on Mark II

### ISSUE THREAD

**Issue by mlc** [rjl20/mastodon#2]
I want to visit oulipo.social now that I can again!

But, I can't pass its two-factor input box, not with my Googl Auth app nor my backup strings. Did a bit of this facility stop with our miraculous 2nd birth? Can you try wiping two-factor codings from my account (`mlc`) or from all such accounts?

**Comment by rjl20** [comment]
Two-factor auth is off for you now; I'll look into if I can do it for all such accounts.

**Comment by mlc** [comment]
hooray! thanks so much!
